Added API endpoint: GET /api/v1/server_info
andylibrian/terjang pull request #12
Opened 2021-06-06 14:33 UTC by ajiprabowo

2021-06-06 23:59 UTC, andylibrian requested changes

2021-06-06 23:59 UTC, andylibrian commented on pkg/server/server.go
> +	router.GET("/api/v1/server_info", s.getServerInfo)
For the sake of consistency

```suggestion
	router.GET("/api/v1/server_info", s.handleServerInfo)
```

2021-06-06 23:59 UTC, andylibrian commented on pkg/server/server.go
> +func (s *Server) getServerInfo(responseWriter http.ResponseWriter, req *http.Request, _ httprouter.Params) {
```suggestion
func (s *Server) handleServerInfo(responseWriter http.ResponseWriter, req *http.Request, _ httprouter.Params) {
```

2021-06-06 23:59 UTC, andylibrian commented on pkg/server/server.go
> +	// Server Info (Body: Json Content-type)
The code is clear enough that this comment is unnecessary
```suggestion
```

2021-06-06 23:59 UTC, andylibrian commented on pkg/server/server.go
> +	//Header: Json Content-type
The code is clear enough that this comment is too verbose
```suggestion
```

2021-06-10 14:01 UTC, ajiprabowo commented on pkg/server/server.go
> +	router.GET("/api/v1/server_info", s.getServerInfo)
Noted

2021-06-10 22:16 UTC, andylibrian approved these changes

2021-06-10 22:16 UTC, merged